version: '3'

services:
  tasksBD:
    image: postgres:15.3
    container_name: tasks-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERS=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data